// Auto-generated by generateComponentMap.js
import AddCustomerReg from './AddCustomerReg.jsx';
import AddDispatchReport from './AddDispatchReport.jsx';
import AddMaterialNote from './AddMaterialNote.jsx';
import AddProduct from './AddProduct.jsx';
import AddReceivingInspectionReport from './AddReceivingInspectionReport.jsx';
import AddRepairProduct from './AddRepairProduct.jsx';
import AddRole from './AddRole.jsx';
import AddUser from './AddUser.jsx';
import ApproveCustomerOrder from './ApproveCustomerOrder.jsx';
import ApproveReceivingInspectionReport from './ApproveReceivingInspectionReport.jsx';
import CustomBreadcrumb from './Breadcrumb/CustomBreadcrumb.jsx';
import CAForm from './CAForm.jsx';
import CheckboxWithTick from './CheckboxWithTick.jsx';
import ViewSupplierRegistration from './Checker/CheckerSupplierRegistration/ViewSupplierRegistration.jsx';
import CheckerTable from './Checker/CheckerTable.jsx';
import Editsupplierform from './Checker/EditSupplier/Editsupplierform.jsx';
import EditSupplierTable from './Checker/EditSupplier/EditSupplierTable.jsx';
import CustomerOrder from './CustomerOrder.jsx';
import EditCAForm from './EditCAForm.jsx';
import EditCAFormTable from './EditCAFormTable.jsx';
import EditCustomerOrderForm from './EditCustomerOrderForm.jsx';
import EditCustomerOrderTable from './EditCustomerOrderTable.jsx';
import EditCustomerRepairProduct from './EditCustomerRepairProduct.jsx';
import EditDispatchReport from './EditDispatchReport.jsx';
import EditInspectionReportForm from './EditInspectionReportForm.jsx';
import EditInspectionReportTable from './EditInspectionReportTable.jsx';
import EditMaterialNote from './EditMaterialNote.jsx';
import EditProduct from './EditProduct.jsx';
import EditRepairProduct from './EditRepairProduct.jsx';
import EditStoreAcceptance from './EditStoreAcceptance.jsx';
import EditUpdateStore from './EditUpdateStore.jsx';
import EditUser from './EditUser.jsx';
import Footer from './Footer.jsx';
import GenerateInspectionReportTable from './GenerateInspectionReportTable.jsx';
import Header from './Header.jsx';
import HomePage from './HomePage.jsx';
import ListProducts from './ListProducts.jsx';
import LoginPage from './LoginPage.jsx';
import MaterialRecipt from './MaterialRecipt.jsx';
import AddMaterialRequisition from './MaterialRequisition/AddMaterialRequisition/AddMaterialRequisition.jsx';
import EditMaterialRequisition from './MaterialRequisition/EditMaterialRequisition/EditMaterialRequisition.jsx';
import index from './MaterialRequisition/MaterialRequisitionReport/index.jsx';
import ViewMaterialRequisition from './MaterialRequisition/ViewMaterialRequisition.jsx';
import ViewMaterialRequistionWO from './MaterialRequisition/ViewMaterialRequistionWO.jsx';
import MyModalComponent from './partials/MyModalComponent.jsx';
import PasswordChange from './PasswordChange.jsx';
import PrivateRoute from './PrivateRoute.jsx';
import ProductList from './ProductList.jsx';
import EditPurchaseOrder from './PurchaseOrder/EditPurchaseOrder/EditPurchaseOrder.jsx';
import PurchaseOrder from './PurchaseOrder/PurchaseOrder.jsx';
import PurchaseOrderForm from './PurchaseOrder/PurchaseOrderForm.jsx';
import PurchaseOrderReport from './PurchaseOrder/PurchaseOrderReport/PurchaseOrderReport.jsx';
import ViewPurchaseOrder from './PurchaseOrder/ViewPurchaseOrder/ViewPurchaseOrder.jsx';
import Addpurchase from './PurchaseRequisition/AddpurchaseRequisition/Addpurchase.jsx';
import EditPurchase from './PurchaseRequisition/EditPurchaseRequisition/EditPurchase.jsx';
import ViewPurchaseRequisition from './PurchaseRequisition/ViewPurchaseRequisition.jsx';
import RoleMenuMapping from './RoleMenuMapping.jsx';
import Sidebar from './Sidebar.jsx';
import StoreAccComponent from './StoreAccComponent.jsx';
import StoreInventory from './StoreInventory.jsx';
import SupplierRegistration from './SupplierRegistration.jsx';
import DocAndProcControl from './tabs/supplier_registration/DocAndProcControl.jsx';
import GeneralTab from './tabs/supplier_registration/GeneralTab.jsx';
import IncomingInspectionTab from './tabs/supplier_registration/IncomingInspectionTab.jsx';
import MaterialAndOther from './tabs/supplier_registration/MaterialAndOther.jsx';
import QualityProcessTab from './tabs/supplier_registration/QualityProcessTab.jsx';
import SupplierAnalysisTab from './tabs/supplier_registration/SupplierAnalysisTab.jsx';
import UpdateStoreTable from './UpdateStoreTable.jsx';
import ViewCAForm from './ViewCAForm.jsx';
import ViewCustomerOrder from './ViewCustomerOrder.jsx';
import ViewCustomerRegList from './ViewCustomerRegList.jsx';
import ViewDispatchReport from './ViewDispatchReport.jsx';
import ViewInspectionReports from './ViewInspectionReports.jsx';
import ViewMaterialNotePage from './ViewMaterialNotePage.jsx';
import ViewProduct from './ViewProduct.jsx';
import ViewRepairProducts from './ViewRepairProducts.jsx';
import ViewStoreAcc from './ViewStoreAcc.jsx';
import ViewSupplierRegis from './ViewSupplierRegis.jsx';
import ViewUser from './ViewUser.jsx';
import AddWorkOrder from './Workorder/AddWorkOrder/AddWorkOrder.jsx';
import editWorkOrder from './Workorder/editWorkOrder.jsx';
import ViewWorkOrder from './Workorder/ViewWorkOrder.jsx';
import ViewWorkOrderClosed from './Workorder/ViewWorkOrderClosed.jsx';
import WorkorderTable from './Workorder/WorkorderTable.jsx';

const componentsMap = {
  "AddCustomerReg": AddCustomerReg,
  "AddDispatchReport": AddDispatchReport,
  "AddMaterialNote": AddMaterialNote,
  "AddProduct": AddProduct,
  "AddReceivingInspectionReport": AddReceivingInspectionReport,
  "AddRepairProduct": AddRepairProduct,
  "AddRole": AddRole,
  "AddUser": AddUser,
  "ApproveCustomerOrder": ApproveCustomerOrder,
  "ApproveReceivingInspectionReport": ApproveReceivingInspectionReport,
  "CustomBreadcrumb": CustomBreadcrumb,
  "CAForm": CAForm,
  "CheckboxWithTick": CheckboxWithTick,
  "ViewSupplierRegistration": ViewSupplierRegistration,
  "CheckerTable": CheckerTable,
  "Editsupplierform": Editsupplierform,
  "EditSupplierTable": EditSupplierTable,
  "CustomerOrder": CustomerOrder,
  "EditCAForm": EditCAForm,
  "EditCAFormTable": EditCAFormTable,
  "EditCustomerOrderForm": EditCustomerOrderForm,
  "EditCustomerOrderTable": EditCustomerOrderTable,
  "EditCustomerRepairProduct": EditCustomerRepairProduct,
  "EditDispatchReport": EditDispatchReport,
  "EditInspectionReportForm": EditInspectionReportForm,
  "EditInspectionReportTable": EditInspectionReportTable,
  "EditMaterialNote": EditMaterialNote,
  "EditProduct": EditProduct,
  "EditRepairProduct": EditRepairProduct,
  "EditStoreAcceptance": EditStoreAcceptance,
  "EditUpdateStore": EditUpdateStore,
  "EditUser": EditUser,
  "Footer": Footer,
  "GenerateInspectionReportTable": GenerateInspectionReportTable,
  "Header": Header,
  "HomePage": HomePage,
  "ListProducts": ListProducts,
  "LoginPage": LoginPage,
  "MaterialRecipt": MaterialRecipt,
  "AddMaterialRequisition": AddMaterialRequisition,
  "EditMaterialRequisition": EditMaterialRequisition,
  "index": index,
  "ViewMaterialRequisition": ViewMaterialRequisition,
  "ViewMaterialRequistionWO": ViewMaterialRequistionWO,
  "MyModalComponent": MyModalComponent,
  "PasswordChange": PasswordChange,
  "PrivateRoute": PrivateRoute,
  "ProductList": ProductList,
  "EditPurchaseOrder": EditPurchaseOrder,
  "PurchaseOrder": PurchaseOrder,
  "PurchaseOrderForm": PurchaseOrderForm,
  "PurchaseOrderReport": PurchaseOrderReport,
  "ViewPurchaseOrder": ViewPurchaseOrder,
  "Addpurchase": Addpurchase,
  "EditPurchase": EditPurchase,
  "ViewPurchaseRequisition": ViewPurchaseRequisition,
  "RoleMenuMapping": RoleMenuMapping,
  "Sidebar": Sidebar,
  "StoreAccComponent": StoreAccComponent,
  "StoreInventory": StoreInventory,
  "SupplierRegistration": SupplierRegistration,
  "DocAndProcControl": DocAndProcControl,
  "GeneralTab": GeneralTab,
  "IncomingInspectionTab": IncomingInspectionTab,
  "MaterialAndOther": MaterialAndOther,
  "QualityProcessTab": QualityProcessTab,
  "SupplierAnalysisTab": SupplierAnalysisTab,
  "UpdateStoreTable": UpdateStoreTable,
  "ViewCAForm": ViewCAForm,
  "ViewCustomerOrder": ViewCustomerOrder,
  "ViewCustomerRegList": ViewCustomerRegList,
  "ViewDispatchReport": ViewDispatchReport,
  "ViewInspectionReports": ViewInspectionReports,
  "ViewMaterialNotePage": ViewMaterialNotePage,
  "ViewProduct": ViewProduct,
  "ViewRepairProducts": ViewRepairProducts,
  "ViewStoreAcc": ViewStoreAcc,
  "ViewSupplierRegis": ViewSupplierRegis,
  "ViewUser": ViewUser,
  "AddWorkOrder": AddWorkOrder,
  "editWorkOrder": editWorkOrder,
  "ViewWorkOrder": ViewWorkOrder,
  "ViewWorkOrderClosed": ViewWorkOrderClosed,
  "WorkorderTable": WorkorderTable,
};

export default componentsMap;
